version: '3.5'

services:
  app:
    build:
      context: '.'
    ports:
      - 81:80
    volumes:
      - .:/var/www/html
    restart:
      unless-stopped
    environment:
      - DB_HOST=database
      - DB_PORT=3306

  database:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9999:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      UPLOAD_LIMIT: 20000000000000000000
    depends_on:
      - database
